version: '3.8'

services:

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://admin:admin151105@db:5432/timetable"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin151105
      POSTGRES_DB: timetable
    ports:
      - "5432:5432"

volumes:
  postgres_data:
